GameStore.WUI/Controllers/CartController.cs
using GameStore.WUI.Models;
using GameStore.WUI.Models.Abstract;
using GameStore.WUI.Models.Concrete;
using System;
using System.Linq;
using System.Web.Mvc;

namespace GameStore.WUI.Controllers
{
    public class CartController : Controller
    {
        private IGameRepository repository; 
        private IOrderProcessor orderProcessor;
 
        public CartController(IGameRepository repository, IOrderProcessor orderProcessor )
        {
            // Initialisation across DI controller ninject
            this.repository = repository;
            this.orderProcessor = orderProcessor;
        }


        // Cart инициализируеться с использованием CartModelBinder в  
        // Global в методе Application_Start() класа MvcApplication 

        public ViewResult Index( Cart cart,string returnUrl)
        {
            return View(new CartIndexViewModel(cart, returnUrl));             
        }

        /// <summary>
        /// Added element in cart wich id and returns url sesion client.
        /// </summary>
        /// <param name="gameId"></param>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        public RedirectToRouteResult AddToCart(Cart cart, int gameId, string returnUrl)
        {
            Game game = repository.Games.FirstOrDefault(g => g.Id == gameId);

            if (game != null)
            {
                cart.AddItem(game, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        /// <summary>
        /// Removes element in cart wich id and returns url sesion client.
        /// </summary>
        /// <param name="gameId"></param>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        public RedirectToRouteResult RemoveFromCart(Cart cart, int gameId, string returnUrl)
        {
            Game game = repository.Games.FirstOrDefault(g => g.Id == gameId);

            if (game != null)
            {
                cart.RemoveLine(game);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
        /// <summary>
        /// Returns rummary cart
        /// </summary>
        /// <param name="cart"></param>
        /// <returns></returns>
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

         //<summary>
         //Payment process checkout
         //</summary>
         //<param name = "cart" ></ param >
         //< param name="shippingDetails"></param>
         //<returns></returns>
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
    }
}

GameStore.WUI/Controllers/NavController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GameStore.WUI.Models.Abstract;
namespace GameStore.WUI.Controllers
{
    public class NavController : Controller
    {
        IGameRepository gameRepositorye;

        public NavController(IGameRepository gameRepository)
        {
            // Initialisation across DI controller ninject
            this.gameRepositorye = gameRepository;
        }
        

        // GET: Nav

            /// <summary>
            /// Selected, sorted and returned catego
            /// </summary>
            /// <param name="category"></param>
            /// <returns></returns>
        public PartialViewResult Menu(string category = null)//, bool horizontalNav = false)
        {
            ViewBag.SelectedCategory = category;


            IEnumerable<string> categories = gameRepositorye.Games
              .Select(game => game.Category)
              .Distinct()
              .OrderBy(x => x);

            //string viewName = horizontalNav ? "MenuHorizontal" : "Menu";

            return PartialView("FlexMenu",categories);
        }
    }
}

GameStore.WUI/Views/Shared/GameSummary.Mobile.cshtml
@model GameStore.WUI.Models.Game
<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>@Model.Name</h2>
    <div>
        <div>
            @Model.Description
        </div>
        <div>
            <strong>(@Model.Price.ToString("# $"))</strong>
        </div>
        <div>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(x => x.Id)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="В корзину" />
            }
        </div>
    </div>
</div>

GameStore.WUI/Views/Shared/GameSummary.cshtml
@model GameStore.WUI.Models.Game

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# $")</span>
    </h3>
 
    @using (@Html.BeginForm( "AddToCart", "Cart"))
    {
        <div class="pull-right">   
                     
            @Html.Hidden("gameId", Model.Id)
            
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)          
          

            <input type="submit" class="btn btn-success" value="Добавить в корзину" />
        </div>
    }

    <span class="lead">@Model.Description</span>
</div>

GameStore.WUI/Views/Shared/Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>GameStore</h3>
            @Html.Action("Menu", "Nav")
        </div>
        <div data-role="content">
            <ul data-role="listview" data-divider-theme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>
</body>
</html>

GameStore.WUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

GameStore.WUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <script type="text/javascript" src="~/scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>
    
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">GameStore - магазин компьютерных игр</a>
        @Html.Action("Summary", "Cart")
            
    </div>
    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { horizontalNav = true })
    </div>

    <div class="row panel">
        <div id="categories" class="col-sm-3 hidden-xs">
                @Html.Action("Menu", "Nav")
            </div>
            <div class="col-xs-12 col-sm-8">
                @RenderBody()

        </div>
    </div>
</body>
</html>

 